services:
    wm_ut.tmp_configurator:
        class: Wikimart\UsefulToolsBundle\Configurator\TmpConfigurator
        arguments: []
    wm_ut.array:
        class: Wikimart\UsefulTools\Helper\ArrayHelper
        arguments: []
    wm_ut.cmd:
        class: Wikimart\UsefulTools\Helper\CmdHelper
        arguments: []
    wm_ut.csv:
        class: Wikimart\UsefulTools\Helper\CsvHelper
        arguments: [@wm_ut.text, @wm_ut.tmp]
    wm_ut.date:
        class: Wikimart\UsefulTools\Helper\DateHelper
        arguments: []
    wm_ut.dir:
        class: Wikimart\UsefulTools\Helper\DirHelper
        arguments: []
    wm_ut.file:
        class: Wikimart\UsefulTools\Helper\FileHelper
        arguments: [@wm_ut.cmd, @wm_ut.tmp, @wm_ut.dir]
    wm_ut.html:
        class: Wikimart\UsefulTools\Helper\HtmlHelper
        arguments: []
    wm_ut.json:
        class: Wikimart\UsefulTools\Helper\JsonHelper
        arguments: []
    wm_ut.text:
        class: Wikimart\UsefulTools\Helper\TextHelper
        arguments: []
    wm_ut.tmp:
        class: Wikimart\UsefulTools\Helper\TmpHelper
        arguments: [@=service('wm_ut.tmp_configurator').getTmpDir()]
    wm_ut.url:
        class: Wikimart\UsefulTools\Helper\UrlHelper
        arguments: [@wm_ut.text]
    wm_ut.xpath:
        class: Wikimart\UsefulTools\Helper\XPathHelper
        arguments: []
    wm_ut.host:
        class: Wikimart\UsefulTools\Helper\HostHelper
        arguments: [@wm_ut.text, @wm_ut.url]
    wm_ut.email:
        class: Wikimart\UsefulTools\Helper\EmailHelper
        arguments: []
    wm_ut.query:
        class: Wikimart\UsefulTools\Helper\QueryHelper
        arguments: []
    wm_ut.socket_addresses:
        class: Wikimart\UsefulTools\Helper\SocketAddressesHelper
        arguments: []
    wm_ut.db:
        class: Wikimart\UsefulTools\Helper\DBHelper
        arguments: ['Pgsql'] # Pgsql, Mysql
